services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: triptailor
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d triptailor"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/nxmbit/trip-tailor-ai/backend:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/triptailor
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_AI_OPENAI_API_KEY=${SPRING_AI_OPENAI_API_KEY}
      - SECURITY_JWT_SECRET_KEY=${SECURITY_JWT_SECRET_KEY}
      - SPRING_OAUTH2_GOOGLE_CLIENT_ID=${SPRING_OAUTH2_GOOGLE_CLIENT_ID}
      - SPRING_OAUTH2_GOOGLE_CLIENT_SECRET=${SPRING_OAUTH2_GOOGLE_CLIENT_SECRET}
      - SPRING_OAUTH2_GITHUB_CLIENT_ID=${SPRING_OAUTH2_GITHUB_CLIENT_ID}
      - SPRING_OAUTH2_GITHUB_CLIENT_SECRET=${SPRING_OAUTH2_GITHUB_CLIENT_SECRET}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - WEB_FRONTEND_URL=${WEB_FRONTEND_URL:-}
      - API_BASE_URL=${WEB_API_BASE_URL}
      - CLIENT_TYPE=WEB
      - FIREBASE_ENABLED=false
    ports:
      - "8080:8080"

  backend-mobile:
    image: ghcr.io/nxmbit/trip-tailor-ai/backend:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/triptailor
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_AI_OPENAI_API_KEY=${SPRING_AI_OPENAI_API_KEY}
      - SECURITY_JWT_SECRET_KEY=${SECURITY_JWT_SECRET_KEY}
      - SPRING_OAUTH2_GOOGLE_CLIENT_ID=${SPRING_OAUTH2_GOOGLE_CLIENT_ID}
      - SPRING_OAUTH2_GOOGLE_CLIENT_SECRET=${SPRING_OAUTH2_GOOGLE_CLIENT_SECRET}
      - SPRING_OAUTH2_GITHUB_CLIENT_ID=${SPRING_OAUTH2_GITHUB_CLIENT_ID}
      - SPRING_OAUTH2_GITHUB_CLIENT_SECRET=${SPRING_OAUTH2_GITHUB_CLIENT_SECRET}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - API_BASE_URL=${MOBILE_API_BASE_URL}
      - CLIENT_TYPE=MOBILE
      - FIREBASE_ENABLED=true
      - MOBILE_REDIRECT_URI=triptailor://oauth2redirect
      - FIREBASE_CREDENTIALS_PATH=/app/firebase/credentials.json
    ports:
      - "8081:8080"
    volumes:
      - ./firebase:/app/firebase

  frontend:
    image: ghcr.io/nxmbit/trip-tailor-ai/frontend:latest
    environment:
      - API_BASE_URL=${WEB_API_BASE_URL}
      - GOOGLE_MAPS_FRONTEND_API_KEY=${GOOGLE_MAPS_FRONTEND_API_KEY}
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres-data: