spring:
  application:
    name: triptailor

  # DB Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${SPRING_OAUTH2_GOOGLE_CLIENT_ID}
            clientSecret: ${SPRING_OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${API_BASE_URL}/login/oauth2/code/google
            scope:
              - email
              - profile
          github:
            clientId: ${SPRING_OAUTH2_GITHUB_CLIENT_ID}
            clientSecret: ${SPRING_OAUTH2_GITHUB_CLIENT_SECRET}
            redirect-uri: ${API_BASE_URL}/login/oauth2/code/github
            scope:
              - user:email
              - read:user

  # AI Configuration
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1

  # Config Import
  config:
    import: optional:file:.env[.properties]

# Logging Configuration
logging:
  level:
    root: ${LOGGING_LEVEL}

# Client Configuration (web or mobile)
# WEB or MOBILE
client:
  type: ${CLIENT_TYPE}

# JWT Configuration
security:
  jwt:
    access-token:
      secret-key: ${SECURITY_JWT_SECRET_KEY}
      token-expiration: 3600000
    refresh-token:
      token-expiration: 604800000
  cors:
    webAllowedOrigins: ${WEB_FRONTEND_URL:}
  oauth2:
    webRedirectUri: ${WEB_FRONTEND_URL:}/#/oauth2/redirect
    mobileRedirectUri: ${MOBILE_REDIRECT_URI:}

# AWS S3 Configuration
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}
    link-expiration: 3600

# Google Maps Configuration
google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}

firebase:
  credentials:
    path: ${FIREBASE_CREDENTIALS_PATH:}
  enabled: ${FIREBASE_ENABLED:false}
